import type { CardProps } from "../components/Card";
export const allPossibleCards: CardProps[] = [
  { color: "red", num: "0", type: "number" },
  { color: "red", num: "1", type: "number" },
  { color: "red", num: "1", type: "number" },
  { color: "red", num: "2", type: "number" },
  { color: "red", num: "2", type: "number" },
  { color: "red", num: "3", type: "number" },
  { color: "red", num: "3", type: "number" },
  { color: "red", num: "4", type: "number" },
  { color: "red", num: "4", type: "number" },
  { color: "red", num: "5", type: "number" },
  { color: "red", num: "5", type: "number" },
  { color: "red", num: "6", type: "number" },
  { color: "red", num: "6", type: "number" },
  { color: "red", num: "7", type: "number" },
  { color: "red", num: "7", type: "number" },
  { color: "red", num: "8", type: "number" },
  { color: "red", num: "8", type: "number" },
  { color: "red", num: "9", type: "number" },
  { color: "red", num: "9", type: "number" },
  { color: "red", type: "skip" },
  { color: "red", type: "skip" },
  { color: "red", type: "reverse" },
  { color: "red", type: "reverse" },
  { color: "red", type: "draw2" },
  { color: "red", type: "draw2" },

  { color: "blue", num: "0", type: "number" },
  { color: "blue", num: "1", type: "number" },
  { color: "blue", num: "1", type: "number" },
  { color: "blue", num: "2", type: "number" },
  { color: "blue", num: "2", type: "number" },
  { color: "blue", num: "3", type: "number" },
  { color: "blue", num: "3", type: "number" },
  { color: "blue", num: "4", type: "number" },
  { color: "blue", num: "4", type: "number" },
  { color: "blue", num: "5", type: "number" },
  { color: "blue", num: "5", type: "number" },
  { color: "blue", num: "6", type: "number" },
  { color: "blue", num: "6", type: "number" },
  { color: "blue", num: "7", type: "number" },
  { color: "blue", num: "7", type: "number" },
  { color: "blue", num: "8", type: "number" },
  { color: "blue", num: "8", type: "number" },
  { color: "blue", num: "9", type: "number" },
  { color: "blue", num: "9", type: "number" },
  { color: "blue", type: "skip" },
  { color: "blue", type: "skip" },
  { color: "blue", type: "reverse" },
  { color: "blue", type: "reverse" },
  { color: "blue", type: "draw2" },
  { color: "blue", type: "draw2" },

  { color: "green", num: "0", type: "number" },
  { color: "green", num: "1", type: "number" },
  { color: "green", num: "1", type: "number" },
  { color: "green", num: "2", type: "number" },
  { color: "green", num: "2", type: "number" },
  { color: "green", num: "3", type: "number" },
  { color: "green", num: "3", type: "number" },
  { color: "green", num: "4", type: "number" },
  { color: "green", num: "4", type: "number" },
  { color: "green", num: "5", type: "number" },
  { color: "green", num: "5", type: "number" },
  { color: "green", num: "6", type: "number" },
  { color: "green", num: "6", type: "number" },
  { color: "green", num: "7", type: "number" },
  { color: "green", num: "7", type: "number" },
  { color: "green", num: "8", type: "number" },
  { color: "green", num: "8", type: "number" },
  { color: "green", num: "9", type: "number" },
  { color: "green", num: "9", type: "number" },
  { color: "green", type: "skip" },
  { color: "green", type: "skip" },
  { color: "green", type: "reverse" },
  { color: "green", type: "reverse" },
  { color: "green", type: "draw2" },
  { color: "green", type: "draw2" },

  { color: "yellow", num: "0", type: "number" },
  { color: "yellow", num: "1", type: "number" },
  { color: "yellow", num: "1", type: "number" },
  { color: "yellow", num: "2", type: "number" },
  { color: "yellow", num: "2", type: "number" },
  { color: "yellow", num: "3", type: "number" },
  { color: "yellow", num: "3", type: "number" },
  { color: "yellow", num: "4", type: "number" },
  { color: "yellow", num: "4", type: "number" },
  { color: "yellow", num: "5", type: "number" },
  { color: "yellow", num: "5", type: "number" },
  { color: "yellow", num: "6", type: "number" },
  { color: "yellow", num: "6", type: "number" },
  { color: "yellow", num: "7", type: "number" },
  { color: "yellow", num: "7", type: "number" },
  { color: "yellow", num: "8", type: "number" },
  { color: "yellow", num: "8", type: "number" },
  { color: "yellow", num: "9", type: "number" },
  { color: "yellow", num: "9", type: "number" },
  { color: "yellow", type: "skip" },
  { color: "yellow", type: "skip" },
  { color: "yellow", type: "reverse" },
  { color: "yellow", type: "reverse" },
  { color: "yellow", type: "draw2" },
  { color: "yellow", type: "draw2" },

  { type: "draw4" },
  { type: "draw4" },
  { type: "draw4" },
  { type: "draw4" },
  { type: "wild" },
  { type: "wild" },
  { type: "wild" },
  { type: "wild" },
];
